"""logo

Revision ID: 71a06eb17167
Revises: f80324ea51cf
Create Date: 2024-03-06 10:13:51.672925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a06eb17167'
down_revision = 'f80324ea51cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salon', sa.Column('addresse', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salon', 'addresse')
    # ### end Alembic commands ###
