"""logo

Revision ID: f4e47d38652d
Revises: 71a06eb17167
Create Date: 2024-03-06 10:14:56.913064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e47d38652d'
down_revision = '71a06eb17167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salon', sa.Column('logo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salon', 'logo')
    # ### end Alembic commands ###
